// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helper.proto

package helper

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/tvducmt/protoc-gen-copy/protobuf"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListCITransactionsRequestB struct {
	MTransId             string   `protobuf:"bytes,1,opt,name=m_trans_id,json=mTransId,proto3" json:"m_trans_id,omitempty"`
	ZpTransId            string   `protobuf:"bytes,2,opt,name=zp_trans_id,json=zpTransId,proto3" json:"zp_trans_id,omitempty"`
	MId                  string   `protobuf:"bytes,3,opt,name=m_id,json=mId,proto3" json:"m_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCITransactionsRequestB) Reset()         { *m = ListCITransactionsRequestB{} }
func (m *ListCITransactionsRequestB) String() string { return proto.CompactTextString(m) }
func (*ListCITransactionsRequestB) ProtoMessage()    {}
func (*ListCITransactionsRequestB) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a5e974ecb0f94b, []int{0}
}

func (m *ListCITransactionsRequestB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCITransactionsRequestB.Unmarshal(m, b)
}
func (m *ListCITransactionsRequestB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCITransactionsRequestB.Marshal(b, m, deterministic)
}
func (m *ListCITransactionsRequestB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCITransactionsRequestB.Merge(m, src)
}
func (m *ListCITransactionsRequestB) XXX_Size() int {
	return xxx_messageInfo_ListCITransactionsRequestB.Size(m)
}
func (m *ListCITransactionsRequestB) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCITransactionsRequestB.DiscardUnknown(m)
}

var xxx_messageInfo_ListCITransactionsRequestB proto.InternalMessageInfo

func (m *ListCITransactionsRequestB) GetMTransId() string {
	if m != nil {
		return m.MTransId
	}
	return ""
}

func (m *ListCITransactionsRequestB) GetZpTransId() string {
	if m != nil {
		return m.ZpTransId
	}
	return ""
}

func (m *ListCITransactionsRequestB) GetMId() string {
	if m != nil {
		return m.MId
	}
	return ""
}

type ListCITransactionsRequestA struct {
	MTransId             string   `protobuf:"bytes,1,opt,name=m_trans_id,json=mTransId,proto3" json:"m_trans_id,omitempty"`
	ZpTransId            string   `protobuf:"bytes,2,opt,name=zp_trans_id,json=zpTransId,proto3" json:"zp_trans_id,omitempty"`
	MerchantId           string   `protobuf:"bytes,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	MId                  string   `protobuf:"bytes,4,opt,name=m_id,json=mId,proto3" json:"m_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCITransactionsRequestA) Reset()         { *m = ListCITransactionsRequestA{} }
func (m *ListCITransactionsRequestA) String() string { return proto.CompactTextString(m) }
func (*ListCITransactionsRequestA) ProtoMessage()    {}
func (*ListCITransactionsRequestA) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9a5e974ecb0f94b, []int{1}
}

func (m *ListCITransactionsRequestA) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCITransactionsRequestA.Unmarshal(m, b)
}
func (m *ListCITransactionsRequestA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCITransactionsRequestA.Marshal(b, m, deterministic)
}
func (m *ListCITransactionsRequestA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCITransactionsRequestA.Merge(m, src)
}
func (m *ListCITransactionsRequestA) XXX_Size() int {
	return xxx_messageInfo_ListCITransactionsRequestA.Size(m)
}
func (m *ListCITransactionsRequestA) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCITransactionsRequestA.DiscardUnknown(m)
}

var xxx_messageInfo_ListCITransactionsRequestA proto.InternalMessageInfo

func (m *ListCITransactionsRequestA) GetMTransId() string {
	if m != nil {
		return m.MTransId
	}
	return ""
}

func (m *ListCITransactionsRequestA) GetZpTransId() string {
	if m != nil {
		return m.ZpTransId
	}
	return ""
}

func (m *ListCITransactionsRequestA) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *ListCITransactionsRequestA) GetMId() string {
	if m != nil {
		return m.MId
	}
	return ""
}

func init() {
	proto.RegisterType((*ListCITransactionsRequestB)(nil), "helper.ListCITransactionsRequestB")
	proto.RegisterType((*ListCITransactionsRequestA)(nil), "helper.ListCITransactionsRequestA")
}

func init() { proto.RegisterFile("helper.proto", fileDescriptor_c9a5e974ecb0f94b) }

var fileDescriptor_c9a5e974ecb0f94b = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0x48, 0xcd, 0x29,
	0x48, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0xa4, 0x2c, 0xd2, 0x33,
	0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0x4b, 0xca, 0x52, 0x4a, 0x93, 0x73, 0x4b,
	0xf4, 0xc1, 0x2a, 0x92, 0x75, 0xd3, 0x53, 0xf3, 0x74, 0x93, 0xf3, 0x0b, 0x2a, 0x21, 0xfc, 0xa4,
	0xd2, 0x34, 0xfd, 0xe4, 0xfc, 0x82, 0x4c, 0x98, 0x09, 0x4a, 0xb9, 0x5c, 0x52, 0x3e, 0x99, 0xc5,
	0x25, 0xce, 0x9e, 0x21, 0x45, 0x89, 0x79, 0xc5, 0x89, 0xc9, 0x25, 0x99, 0xf9, 0x79, 0xc5, 0x41,
	0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x4e, 0x42, 0x32, 0x5c, 0x5c, 0xb9, 0xf1, 0x25, 0x20, 0x99,
	0xf8, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x8e, 0x5c, 0xb0, 0x52, 0xcf, 0x14,
	0x21, 0x39, 0x2e, 0xee, 0xaa, 0x02, 0x84, 0x34, 0x13, 0x58, 0x9a, 0xb3, 0xaa, 0x00, 0x26, 0x2f,
	0xc8, 0xc5, 0x92, 0x0b, 0x92, 0x60, 0x06, 0x4b, 0x30, 0xe7, 0x7a, 0xa6, 0x28, 0xf5, 0x31, 0xe2,
	0xb1, 0xcf, 0x91, 0x42, 0xfb, 0xe4, 0xb9, 0xb8, 0x73, 0x53, 0x8b, 0x92, 0x33, 0x12, 0xf3, 0x4a,
	0x10, 0xd6, 0x72, 0xc1, 0x84, 0x90, 0x1c, 0xc4, 0x02, 0x77, 0x50, 0x12, 0x1b, 0x38, 0x18, 0x8c,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x67, 0xe7, 0x41, 0xd8, 0x58, 0x01, 0x00, 0x00,
}
