// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: copiertest.proto

package test

import (
	flag "flag"
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
	_ "github.com/tvducmt/protoc-gen-copy/helper"
	helper "github.com/tvducmt/protoc-gen-copy/helper"
	_ "github.com/tvducmt/protoc-gen-copy/protobuf"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *CopyProtoAB) Copy(to *helper.ListCITransactionsRequestB, from *helper.ListCITransactionsRequestA) {
	flag.Parse()
	to.MTransId = from.MTransId
	to.ZpTransId = from.ZpTransId
	to.MId = from.MId
}
