// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: copy.proto

package copy

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/grpc"
	context "context"
	reflect "reflect"
	core_service "github.com/tvducmt/protoc-gen-copy/protobuf-file/core-service"
	middleware "github.com/tvducmt/protoc-gen-copy/protobuf-file/middleware"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context

func isNil(field interface{}) bool {
	zero := reflect.Zero(reflect.TypeOf(field)).Interface()
	if reflect.DeepEqual(field, zero) {
		return true
	}
	return false
}

type copy struct {
}

func NewCopy() *copy {
	return &copy{}
}

func (c *copy) ListCITransactionsRequest(from *middleware.BODetailReconciliation, to *core_service.BODetailReconciliation) error {
	if !isNil(from.CountableAttribute) {
		to.CountableAttribute = &core_service.BODetailReconciliation_CountableAttribute{
			RefundApi: func(h *middleware.BODetailReconciliation_CountableAttribute) core_service.RefundTransLogApi {
				if h == nil {
					return 0
				}
				return core_service.RefundTransLogApi(h.RefundApi)
			}(from.CountableAttribute),
			Data: &core_service.BODetailReconciliation_CountableAttribute_Transaction{
				K1: func(h *middleware.BODetailReconciliation_CountableAttribute_Transaction) string {
					if h == nil {
						return reflect.Zero(reflect.TypeOf(reflect.String)).Interface().(string)
					}
					return h.K1
				}(from.CountableAttribute.Data),
				K2: func(h *middleware.BODetailReconciliation_CountableAttribute_Transaction) string {
					if h == nil {
						return reflect.Zero(reflect.TypeOf(reflect.String)).Interface().(string)
					}
					return h.K2
				}(from.CountableAttribute.Data),
				Stm: &core_service.Statement{
					H1: func(h *middleware.Statement) string {
						if h == nil {
							return reflect.Zero(reflect.TypeOf(reflect.String)).Interface().(string)
						}
						return h.H1
					}(from.CountableAttribute.Data.Stm),
					H2: func(h *middleware.Statement) string {
						if h == nil {
							return reflect.Zero(reflect.TypeOf(reflect.String)).Interface().(string)
						}
						return h.H2
					}(from.CountableAttribute.Data.Stm),
				},
			},
			TpeBankCode: func(h *middleware.BODetailReconciliation_CountableAttribute) string {
				if h == nil {
					return reflect.Zero(reflect.TypeOf(reflect.String)).Interface().(string)
				}
				return h.TpeBankCode
			}(from.CountableAttribute),
			Stm: &core_service.Statement{},
			ItemCount: func(h *middleware.BODetailReconciliation_CountableAttribute) int32 {
				if h == nil {
					return reflect.Zero(reflect.TypeOf(reflect.Int32)).Interface().(int32)
				}
				return h.ItemCount
			}(from.CountableAttribute),
		}
	}
	return nil
}
