// Code generated by protoc-gen-go. DO NOT EDIT.
// source: copy.proto

package copy

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/tvducmt/protoc-gen-copy/protobuf"
	core_service "github.com/tvducmt/protoc-gen-copy/protobuf-file/core-service"
	middleware "github.com/tvducmt/protoc-gen-copy/protobuf-file/middleware"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("copy.proto", fileDescriptor_8b8564a7da00bcc7) }

var fileDescriptor_8b8564a7da00bcc7 = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x8e, 0xbd, 0x0e, 0x82, 0x30,
	0x14, 0x85, 0x1d, 0x88, 0x43, 0x47, 0x36, 0x59, 0x4c, 0x4c, 0x1c, 0xdb, 0x26, 0xba, 0xb8, 0xb3,
	0x68, 0xc2, 0x64, 0x7c, 0x01, 0xb8, 0x5c, 0xb0, 0x09, 0xe5, 0xd6, 0xfe, 0x60, 0x78, 0x7b, 0x03,
	0x75, 0x60, 0x61, 0x60, 0x3b, 0x27, 0x3d, 0xdf, 0xd7, 0xcb, 0x18, 0x90, 0x19, 0x85, 0xb1, 0xe4,
	0x29, 0x4d, 0xa6, 0x9c, 0xdd, 0x5a, 0xe5, 0xdf, 0xa1, 0x12, 0x40, 0x5a, 0xfa, 0xa1, 0x0e, 0xa0,
	0xbd, 0x9c, 0xdf, 0x81, 0xb7, 0xd8, 0xf3, 0x69, 0x13, 0x7b, 0x15, 0x1a, 0x09, 0x64, 0x14, 0xda,
	0xc8, 0x67, 0xf7, 0x0d, 0x24, 0x6f, 0x54, 0x87, 0x12, 0xc8, 0x22, 0x77, 0x68, 0x07, 0x05, 0xb1,
	0xfc, 0x4d, 0xc5, 0x66, 0x93, 0x56, 0x75, 0xdd, 0xe1, 0xb7, 0xb4, 0xcb, 0x18, 0x6d, 0x17, 0xcd,
	0x92, 0x9c, 0xcc, 0x98, 0x22, 0x3b, 0x14, 0xca, 0xf9, 0xfc, 0xf1, 0xb2, 0x65, 0xef, 0x4a, 0xf0,
	0x8a, 0x7a, 0xf7, 0xc4, 0x4f, 0x40, 0xe7, 0xd3, 0xb3, 0x58, 0x70, 0xab, 0xb3, 0xec, 0x28, 0xe6,
	0x33, 0x57, 0x07, 0xa7, 0x5d, 0xb5, 0x9f, 0x7f, 0xbd, 0xfe, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe4,
	0x6c, 0x38, 0x1f, 0x5b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CopyClient is the client API for Copy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CopyClient interface {
	ListCITransactionsRequest(ctx context.Context, in *middleware.ListCITransactionsRequest, opts ...grpc.CallOption) (*core_service.ListCITransactionsRequest, error)
}

type copyClient struct {
	cc *grpc.ClientConn
}

func NewCopyClient(cc *grpc.ClientConn) CopyClient {
	return &copyClient{cc}
}

func (c *copyClient) ListCITransactionsRequest(ctx context.Context, in *middleware.ListCITransactionsRequest, opts ...grpc.CallOption) (*core_service.ListCITransactionsRequest, error) {
	out := new(core_service.ListCITransactionsRequest)
	err := c.cc.Invoke(ctx, "/copy.Copy/ListCITransactionsRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CopyServer is the server API for Copy service.
type CopyServer interface {
	ListCITransactionsRequest(context.Context, *middleware.ListCITransactionsRequest) (*core_service.ListCITransactionsRequest, error)
}

// UnimplementedCopyServer can be embedded to have forward compatible implementations.
type UnimplementedCopyServer struct {
}

func (*UnimplementedCopyServer) ListCITransactionsRequest(ctx context.Context, req *middleware.ListCITransactionsRequest) (*core_service.ListCITransactionsRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCITransactionsRequest not implemented")
}

func RegisterCopyServer(s *grpc.Server, srv CopyServer) {
	s.RegisterService(&_Copy_serviceDesc, srv)
}

func _Copy_ListCITransactionsRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(middleware.ListCITransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CopyServer).ListCITransactionsRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/copy.Copy/ListCITransactionsRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CopyServer).ListCITransactionsRequest(ctx, req.(*middleware.ListCITransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Copy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "copy.Copy",
	HandlerType: (*CopyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCITransactionsRequest",
			Handler:    _Copy_ListCITransactionsRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "copy.proto",
}
