// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: copy.proto

package copy

import (
	context "context"
	fmt "fmt"
	math "math"
	reflect "reflect"

	git_zapa_cloud_merchant_tools_helper_proto "git.zapa.cloud/merchant-tools/helper/proto"
	proto "github.com/gogo/protobuf/proto"
	"github.com/golang/protobuf/ptypes/timestamp"
	"github.com/tvducmt/protoc-gen-copy/protobuf-file/core-service"
	core_service "github.com/tvducmt/protoc-gen-copy/protobuf-file/core-service"
	middleware "github.com/tvducmt/protoc-gen-copy/protobuf-file/middleware"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context

func isNil(field interface{}) bool {
	zero := reflect.Zero(reflect.TypeOf(field)).Interface()
	if reflect.DeepEqual(field, zero) {
		return true
	}
	return false
}

type copy struct {
}

func NewCopy() *copy {
	return &copy{}
}

func (c *copy) ListCITransactionsRequest(from *middleware.BODetailReconciliation, to *core_service.BODetailReconciliation) error {
	if !isNil(from.FromDate) {
		to.FromDate = &git_zapa_cloud_merchant_tools_helper_proto.Date{
			Year: func(h *git_zapa_cloud_merchant_tools_helper_proto.Date) int32 {
				if h == nil {
					return reflect.Zero(reflect.TypeOf(reflect.Int32)).Interface().(int32)
				}
				return h.Year
			}(from.FromDate),
			Month: func(h *git_zapa_cloud_merchant_tools_helper_proto.Date) int32 {
				if h == nil {
					return reflect.Zero(reflect.TypeOf(reflect.Int32)).Interface().(int32)
				}
				return h.Month
			}(from.FromDate),
			Day: func(h *git_zapa_cloud_merchant_tools_helper_proto.Date) int32 {
				if h == nil {
					return reflect.Zero(reflect.TypeOf(reflect.Int32)).Interface().(int32)
				}
				return h.Day
			}(from.FromDate),
		}
	}
	if !isNil(from.CountableAttribute) {
		to.CountableAttribute = &core.BODetailReconciliation_CountableAttribute{
			Data: &core.BODetailReconciliation_CountableAttribute_Data{
				K1: func(h *middleware.BODetailReconciliation_CountableAttribute_Data) string {
					if h == nil {
						return reflect.Zero(reflect.TypeOf(reflect.String)).Interface().(string)
					}
					return h.K1
				}(from.CountableAttribute.Data),
				K2: func(h *middleware.BODetailReconciliation_CountableAttribute_Data) string {
					if h == nil {
						return reflect.Zero(reflect.TypeOf(reflect.String)).Interface().(string)
					}
					return h.K2
				}(from.CountableAttribute.Data),
				Hello: &core.Hello{
					H1: func(h *middleware.Hello) string {
						if h == nil {
							return reflect.Zero(reflect.TypeOf(reflect.String)).Interface().(string)
						}
						return h.H1
					}(from.CountableAttribute.Data.Hello),
					H2: func(h *middleware.Hello) string {
						if h == nil {
							return reflect.Zero(reflect.TypeOf(reflect.String)).Interface().(string)
						}
						return h.H2
					}(from.CountableAttribute.Data.Hello),
				},
				Hi: &core.BODetailReconciliation_CountableAttribute_Hi{},
			},
			TpeBankCode: func(h *middleware.BODetailReconciliation_CountableAttribute) string {
				if h == nil {
					return reflect.Zero(reflect.TypeOf(reflect.String)).Interface().(string)
				}
				return h.TpeBankCode
			}(from.CountableAttribute),
			Hello: &core.Hello{},
			ItemCount: func(h *middleware.BODetailReconciliation_CountableAttribute) int32 {
				if h == nil {
					return reflect.Zero(reflect.TypeOf(reflect.Int32)).Interface().(int32)
				}
				return h.ItemCount
			}(from.CountableAttribute),
		}
	}
	if !isNil(from.TransTime) {
		to.TransTime = &timestamp.Timestamp{
			Seconds: func(h *timestamp.Timestamp) int64 {
				if h == nil {
					return reflect.Zero(reflect.TypeOf(reflect.Int64)).Interface().(int64)
				}
				return h.Seconds
			}(from.TransTime),
			Nanos: func(h *timestamp.Timestamp) int32 {
				if h == nil {
					return reflect.Zero(reflect.TypeOf(reflect.Int32)).Interface().(int32)
				}
				return h.Nanos
			}(from.TransTime),
		}
	}
	return nil
}
