// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: copier.proto

package copier_proto

import (
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
	descriptor "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type CopyProto struct {
	EnableCpProto        string   `protobuf:"bytes,1,opt,name=enableCpProto,proto3" json:"enableCpProto,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyProto) Reset()         { *m = CopyProto{} }
func (m *CopyProto) String() string { return proto.CompactTextString(m) }
func (*CopyProto) ProtoMessage()    {}
func (*CopyProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_a34944e698b293f0, []int{0}
}
func (m *CopyProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyProto.Unmarshal(m, b)
}
func (m *CopyProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyProto.Marshal(b, m, deterministic)
}
func (m *CopyProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyProto.Merge(m, src)
}
func (m *CopyProto) XXX_Size() int {
	return xxx_messageInfo_CopyProto.Size(m)
}
func (m *CopyProto) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyProto.DiscardUnknown(m)
}

var xxx_messageInfo_CopyProto proto.InternalMessageInfo

func (m *CopyProto) GetEnableCpProto() string {
	if m != nil {
		return m.EnableCpProto
	}
	return ""
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*CopyProto)(nil),
	Field:         66663,
	Name:          "copier_proto.field",
	Tag:           "bytes,66663,opt,name=field",
	Filename:      "copier.proto",
}

func init() {
	proto.RegisterType((*CopyProto)(nil), "copier_proto.CopyProto")
	proto.RegisterExtension(E_Field)
}

func init() { proto.RegisterFile("copier.proto", fileDescriptor_a34944e698b293f0) }

var fileDescriptor_a34944e698b293f0 = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0x2f, 0xc8,
	0x4c, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x82, 0xf2, 0xe2, 0xc1, 0x3c, 0x29, 0x85,
	0xf4, 0xfc, 0xfc, 0xf4, 0x9c, 0x54, 0x7d, 0x30, 0x2f, 0xa9, 0x34, 0x4d, 0x3f, 0x25, 0xb5, 0x38,
	0xb9, 0x28, 0xb3, 0xa0, 0x24, 0x1f, 0xaa, 0x5e, 0xc9, 0x90, 0x8b, 0xd3, 0x39, 0xbf, 0xa0, 0x32,
	0x00, 0xac, 0x59, 0x85, 0x8b, 0x37, 0x35, 0x2f, 0x31, 0x29, 0x27, 0xd5, 0xb9, 0x00, 0x2c, 0x20,
	0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x84, 0x2a, 0x68, 0xe5, 0xc7, 0xc5, 0x9a, 0x96, 0x99, 0x9a,
	0x93, 0x22, 0x24, 0xab, 0x07, 0x31, 0x5e, 0x0f, 0x66, 0xbc, 0x9e, 0x1b, 0x48, 0xdc, 0xbf, 0xa0,
	0x24, 0x33, 0x3f, 0xaf, 0x58, 0xe2, 0x79, 0x07, 0x8b, 0x02, 0xa3, 0x06, 0xb7, 0x91, 0xb8, 0x1e,
	0xb2, 0x9b, 0xf4, 0xe0, 0xd6, 0x05, 0x41, 0x8c, 0x71, 0xe2, 0x8b, 0x42, 0xf1, 0x42, 0x12, 0x1b,
	0x98, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xd5, 0x9b, 0x1e, 0xb0, 0xd9, 0x00, 0x00, 0x00,
}
