// Code generated by protoc-gen-go. DO NOT EDIT.
// source: copier.proto

package copier_proto

import (
	fmt "fmt"
	math "math"

	proto "github.com/gogo/protobuf/proto"
	descriptor "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
// const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CpRule struct {
	MsgCp                string   `protobuf:"bytes,1,opt,name=msg_cp,json=msgCp,proto3" json:"msg_cp,omitempty"`
	ArrMsgCp             string   `protobuf:"bytes,2,opt,name=arr_msg_cp,json=arrMsgCp,proto3" json:"arr_msg_cp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CpRule) Reset()         { *m = CpRule{} }
func (m *CpRule) String() string { return proto.CompactTextString(m) }
func (*CpRule) ProtoMessage()    {}
func (*CpRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_a34944e698b293f0, []int{0}
}

func (m *CpRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CpRule.Unmarshal(m, b)
}
func (m *CpRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CpRule.Marshal(b, m, deterministic)
}
func (m *CpRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CpRule.Merge(m, src)
}
func (m *CpRule) XXX_Size() int {
	return xxx_messageInfo_CpRule.Size(m)
}
func (m *CpRule) XXX_DiscardUnknown() {
	xxx_messageInfo_CpRule.DiscardUnknown(m)
}

var xxx_messageInfo_CpRule proto.InternalMessageInfo

func (m *CpRule) GetMsgCp() string {
	if m != nil {
		return m.MsgCp
	}
	return ""
}

func (m *CpRule) GetArrMsgCp() string {
	if m != nil {
		return m.ArrMsgCp
	}
	return ""
}

var E_Cp = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*CpRule)(nil),
	Field:         72295728,
	Name:          "copier_proto.cp",
	Tag:           "bytes,72295728,opt,name=cp",
	Filename:      "copier.proto",
}

func init() {
	proto.RegisterType((*CpRule)(nil), "copier_proto.CpRule")
	proto.RegisterExtension(E_Cp)
}

func init() { proto.RegisterFile("copier.proto", fileDescriptor_a34944e698b293f0) }

var fileDescriptor_a34944e698b293f0 = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0x2f, 0xc8,
	0x4c, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x82, 0xf2, 0xe2, 0xc1, 0x3c, 0x29, 0x85,
	0xf4, 0xfc, 0xfc, 0xf4, 0x9c, 0x54, 0x7d, 0x30, 0x2f, 0xa9, 0x34, 0x4d, 0x3f, 0x25, 0xb5, 0x38,
	0xb9, 0x28, 0xb3, 0xa0, 0x24, 0x1f, 0xaa, 0x5e, 0xc9, 0x96, 0x8b, 0xcd, 0xb9, 0x20, 0xa8, 0x34,
	0x27, 0x55, 0x48, 0x94, 0x8b, 0x2d, 0xb7, 0x38, 0x3d, 0x3e, 0xb9, 0x40, 0x82, 0x51, 0x81, 0x51,
	0x83, 0x33, 0x88, 0x35, 0xb7, 0x38, 0xdd, 0xb9, 0x40, 0x48, 0x86, 0x8b, 0x2b, 0xb1, 0xa8, 0x28,
	0x1e, 0x2a, 0xc5, 0x04, 0x96, 0xe2, 0x48, 0x2c, 0x2a, 0xf2, 0x05, 0xc9, 0x5a, 0xb9, 0x73, 0x31,
	0x25, 0x17, 0x08, 0xc9, 0xe9, 0x41, 0xec, 0xd1, 0x83, 0xd9, 0xa3, 0xe7, 0x9b, 0x5a, 0x92, 0x91,
	0x9f, 0xe2, 0x5f, 0x50, 0x92, 0x99, 0x9f, 0x57, 0x2c, 0xb1, 0xe1, 0xd4, 0x1e, 0x25, 0x05, 0x46,
	0x0d, 0x6e, 0x23, 0x11, 0x3d, 0x64, 0xe7, 0xe9, 0x41, 0x6c, 0x0e, 0x62, 0x4a, 0x2e, 0x70, 0xe2,
	0x8b, 0x42, 0xf1, 0x47, 0x12, 0x1b, 0x98, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x5d,
	0x10, 0xdc, 0xde, 0x00, 0x00, 0x00,
}
