// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: core.proto

package core_service

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type RefundTransLogApi int32

const (
	RefundTransLogApi_RTA_UNSPECIFIED RefundTransLogApi = 0
	RefundTransLogApi_RTA_FULL        RefundTransLogApi = 1
	RefundTransLogApi_RTA_PARTIAL     RefundTransLogApi = 2
)

var RefundTransLogApi_name = map[int32]string{
	0: "RTA_UNSPECIFIED",
	1: "RTA_FULL",
	2: "RTA_PARTIAL",
}

var RefundTransLogApi_value = map[string]int32{
	"RTA_UNSPECIFIED": 0,
	"RTA_FULL":        1,
	"RTA_PARTIAL":     2,
}

func (x RefundTransLogApi) String() string {
	return proto.EnumName(RefundTransLogApi_name, int32(x))
}

func (RefundTransLogApi) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{0}
}

type BODetailReconciliation_VoucherCode int32

const (
	BODetailReconciliation_VOUCHER_CODE_UNSPECIFICED BODetailReconciliation_VoucherCode = 0
	BODetailReconciliation_VC_YES                    BODetailReconciliation_VoucherCode = 1
	BODetailReconciliation_VC_NO                     BODetailReconciliation_VoucherCode = 2
)

var BODetailReconciliation_VoucherCode_name = map[int32]string{
	0: "VOUCHER_CODE_UNSPECIFICED",
	1: "VC_YES",
	2: "VC_NO",
}

var BODetailReconciliation_VoucherCode_value = map[string]int32{
	"VOUCHER_CODE_UNSPECIFICED": 0,
	"VC_YES":                    1,
	"VC_NO":                     2,
}

func (x BODetailReconciliation_VoucherCode) String() string {
	return proto.EnumName(BODetailReconciliation_VoucherCode_name, int32(x))
}

func (BODetailReconciliation_VoucherCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{0, 0}
}

type BODetailReconciliation struct {
	// google.type.Date from_date               = 1;
	TransTime            *timestamp.Timestamp                       `protobuf:"bytes,2,opt,name=trans_time,json=transTime,proto3" json:"trans_time,omitempty"`
	ZpSystemName         string                                     `protobuf:"bytes,3,opt,name=zp_system_name,json=zpSystemName,proto3" json:"zp_system_name,omitempty"`
	VoucherCode          BODetailReconciliation_VoucherCode         `protobuf:"varint,10,opt,name=voucher_code,json=voucherCode,proto3,enum=core_service.BODetailReconciliation_VoucherCode" json:"voucher_code,omitempty"`
	TimeAttribute        *BODetailReconciliation_TimeAttribute      `protobuf:"bytes,13,opt,name=time_attribute,json=timeAttribute,proto3" json:"time_attribute,omitempty"`
	CountableAttribute   *BODetailReconciliation_CountableAttribute `protobuf:"bytes,14,opt,name=countable_attribute,json=countableAttribute,proto3" json:"countable_attribute,omitempty"`
	P1                   *BODetailReconciliation_Profile            `protobuf:"bytes,5,opt,name=p1,proto3" json:"p1,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                   `json:"-"`
	XXX_unrecognized     []byte                                     `json:"-"`
	XXX_sizecache        int32                                      `json:"-"`
}

func (m *BODetailReconciliation) Reset()         { *m = BODetailReconciliation{} }
func (m *BODetailReconciliation) String() string { return proto.CompactTextString(m) }
func (*BODetailReconciliation) ProtoMessage()    {}
func (*BODetailReconciliation) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{0}
}
func (m *BODetailReconciliation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BODetailReconciliation.Unmarshal(m, b)
}
func (m *BODetailReconciliation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BODetailReconciliation.Marshal(b, m, deterministic)
}
func (m *BODetailReconciliation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BODetailReconciliation.Merge(m, src)
}
func (m *BODetailReconciliation) XXX_Size() int {
	return xxx_messageInfo_BODetailReconciliation.Size(m)
}
func (m *BODetailReconciliation) XXX_DiscardUnknown() {
	xxx_messageInfo_BODetailReconciliation.DiscardUnknown(m)
}

var xxx_messageInfo_BODetailReconciliation proto.InternalMessageInfo

func (m *BODetailReconciliation) GetTransTime() *timestamp.Timestamp {
	if m != nil {
		return m.TransTime
	}
	return nil
}

func (m *BODetailReconciliation) GetZpSystemName() string {
	if m != nil {
		return m.ZpSystemName
	}
	return ""
}

func (m *BODetailReconciliation) GetVoucherCode() BODetailReconciliation_VoucherCode {
	if m != nil {
		return m.VoucherCode
	}
	return BODetailReconciliation_VOUCHER_CODE_UNSPECIFICED
}

func (m *BODetailReconciliation) GetTimeAttribute() *BODetailReconciliation_TimeAttribute {
	if m != nil {
		return m.TimeAttribute
	}
	return nil
}

func (m *BODetailReconciliation) GetCountableAttribute() *BODetailReconciliation_CountableAttribute {
	if m != nil {
		return m.CountableAttribute
	}
	return nil
}

func (m *BODetailReconciliation) GetP1() *BODetailReconciliation_Profile {
	if m != nil {
		return m.P1
	}
	return nil
}

type BODetailReconciliation_TimeAttribute struct {
	RetryTime            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=retry_time,json=retryTime,proto3" json:"retry_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BODetailReconciliation_TimeAttribute) Reset()         { *m = BODetailReconciliation_TimeAttribute{} }
func (m *BODetailReconciliation_TimeAttribute) String() string { return proto.CompactTextString(m) }
func (*BODetailReconciliation_TimeAttribute) ProtoMessage()    {}
func (*BODetailReconciliation_TimeAttribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{0, 0}
}
func (m *BODetailReconciliation_TimeAttribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BODetailReconciliation_TimeAttribute.Unmarshal(m, b)
}
func (m *BODetailReconciliation_TimeAttribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BODetailReconciliation_TimeAttribute.Marshal(b, m, deterministic)
}
func (m *BODetailReconciliation_TimeAttribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BODetailReconciliation_TimeAttribute.Merge(m, src)
}
func (m *BODetailReconciliation_TimeAttribute) XXX_Size() int {
	return xxx_messageInfo_BODetailReconciliation_TimeAttribute.Size(m)
}
func (m *BODetailReconciliation_TimeAttribute) XXX_DiscardUnknown() {
	xxx_messageInfo_BODetailReconciliation_TimeAttribute.DiscardUnknown(m)
}

var xxx_messageInfo_BODetailReconciliation_TimeAttribute proto.InternalMessageInfo

func (m *BODetailReconciliation_TimeAttribute) GetRetryTime() *timestamp.Timestamp {
	if m != nil {
		return m.RetryTime
	}
	return nil
}

type BODetailReconciliation_CountableAttribute struct {
	RefundApi            *RefundApi                                             `protobuf:"bytes,18,opt,name=refund_api,json=refundApi,proto3" json:"refund_api,omitempty"`
	Data                 *BODetailReconciliation_CountableAttribute_Transaction `protobuf:"bytes,20,opt,name=data,proto3" json:"data,omitempty"`
	TpeBankCode          string                                                 `protobuf:"bytes,36,opt,name=tpe_bank_code,json=tpeBankCode,proto3" json:"tpe_bank_code,omitempty"`
	Stm                  *Statement                                             `protobuf:"bytes,3,opt,name=stm,proto3" json:"stm,omitempty"`
	ItemCount            int32                                                  `protobuf:"varint,38,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                               `json:"-"`
	XXX_unrecognized     []byte                                                 `json:"-"`
	XXX_sizecache        int32                                                  `json:"-"`
}

func (m *BODetailReconciliation_CountableAttribute) Reset() {
	*m = BODetailReconciliation_CountableAttribute{}
}
func (m *BODetailReconciliation_CountableAttribute) String() string { return proto.CompactTextString(m) }
func (*BODetailReconciliation_CountableAttribute) ProtoMessage()    {}
func (*BODetailReconciliation_CountableAttribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{0, 1}
}
func (m *BODetailReconciliation_CountableAttribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BODetailReconciliation_CountableAttribute.Unmarshal(m, b)
}
func (m *BODetailReconciliation_CountableAttribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BODetailReconciliation_CountableAttribute.Marshal(b, m, deterministic)
}
func (m *BODetailReconciliation_CountableAttribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BODetailReconciliation_CountableAttribute.Merge(m, src)
}
func (m *BODetailReconciliation_CountableAttribute) XXX_Size() int {
	return xxx_messageInfo_BODetailReconciliation_CountableAttribute.Size(m)
}
func (m *BODetailReconciliation_CountableAttribute) XXX_DiscardUnknown() {
	xxx_messageInfo_BODetailReconciliation_CountableAttribute.DiscardUnknown(m)
}

var xxx_messageInfo_BODetailReconciliation_CountableAttribute proto.InternalMessageInfo

func (m *BODetailReconciliation_CountableAttribute) GetRefundApi() *RefundApi {
	if m != nil {
		return m.RefundApi
	}
	return nil
}

func (m *BODetailReconciliation_CountableAttribute) GetData() *BODetailReconciliation_CountableAttribute_Transaction {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *BODetailReconciliation_CountableAttribute) GetTpeBankCode() string {
	if m != nil {
		return m.TpeBankCode
	}
	return ""
}

func (m *BODetailReconciliation_CountableAttribute) GetStm() *Statement {
	if m != nil {
		return m.Stm
	}
	return nil
}

func (m *BODetailReconciliation_CountableAttribute) GetItemCount() int32 {
	if m != nil {
		return m.ItemCount
	}
	return 0
}

type BODetailReconciliation_CountableAttribute_Transaction struct {
	K1                   string     `protobuf:"bytes,1,opt,name=k1,proto3" json:"k1,omitempty"`
	K2                   string     `protobuf:"bytes,2,opt,name=k2,proto3" json:"k2,omitempty"`
	Stm                  *Statement `protobuf:"bytes,3,opt,name=stm,proto3" json:"stm,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BODetailReconciliation_CountableAttribute_Transaction) Reset() {
	*m = BODetailReconciliation_CountableAttribute_Transaction{}
}
func (m *BODetailReconciliation_CountableAttribute_Transaction) String() string {
	return proto.CompactTextString(m)
}
func (*BODetailReconciliation_CountableAttribute_Transaction) ProtoMessage() {}
func (*BODetailReconciliation_CountableAttribute_Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{0, 1, 0}
}
func (m *BODetailReconciliation_CountableAttribute_Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BODetailReconciliation_CountableAttribute_Transaction.Unmarshal(m, b)
}
func (m *BODetailReconciliation_CountableAttribute_Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BODetailReconciliation_CountableAttribute_Transaction.Marshal(b, m, deterministic)
}
func (m *BODetailReconciliation_CountableAttribute_Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BODetailReconciliation_CountableAttribute_Transaction.Merge(m, src)
}
func (m *BODetailReconciliation_CountableAttribute_Transaction) XXX_Size() int {
	return xxx_messageInfo_BODetailReconciliation_CountableAttribute_Transaction.Size(m)
}
func (m *BODetailReconciliation_CountableAttribute_Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_BODetailReconciliation_CountableAttribute_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_BODetailReconciliation_CountableAttribute_Transaction proto.InternalMessageInfo

func (m *BODetailReconciliation_CountableAttribute_Transaction) GetK1() string {
	if m != nil {
		return m.K1
	}
	return ""
}

func (m *BODetailReconciliation_CountableAttribute_Transaction) GetK2() string {
	if m != nil {
		return m.K2
	}
	return ""
}

func (m *BODetailReconciliation_CountableAttribute_Transaction) GetStm() *Statement {
	if m != nil {
		return m.Stm
	}
	return nil
}

type BODetailReconciliation_Profile struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BODetailReconciliation_Profile) Reset()         { *m = BODetailReconciliation_Profile{} }
func (m *BODetailReconciliation_Profile) String() string { return proto.CompactTextString(m) }
func (*BODetailReconciliation_Profile) ProtoMessage()    {}
func (*BODetailReconciliation_Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{0, 2}
}
func (m *BODetailReconciliation_Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BODetailReconciliation_Profile.Unmarshal(m, b)
}
func (m *BODetailReconciliation_Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BODetailReconciliation_Profile.Marshal(b, m, deterministic)
}
func (m *BODetailReconciliation_Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BODetailReconciliation_Profile.Merge(m, src)
}
func (m *BODetailReconciliation_Profile) XXX_Size() int {
	return xxx_messageInfo_BODetailReconciliation_Profile.Size(m)
}
func (m *BODetailReconciliation_Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_BODetailReconciliation_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_BODetailReconciliation_Profile proto.InternalMessageInfo

func (m *BODetailReconciliation_Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Statement struct {
	H1                   string   `protobuf:"bytes,1,opt,name=h1,proto3" json:"h1,omitempty"`
	H2                   string   `protobuf:"bytes,2,opt,name=h2,proto3" json:"h2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Statement) Reset()         { *m = Statement{} }
func (m *Statement) String() string { return proto.CompactTextString(m) }
func (*Statement) ProtoMessage()    {}
func (*Statement) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{1}
}
func (m *Statement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Statement.Unmarshal(m, b)
}
func (m *Statement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Statement.Marshal(b, m, deterministic)
}
func (m *Statement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Statement.Merge(m, src)
}
func (m *Statement) XXX_Size() int {
	return xxx_messageInfo_Statement.Size(m)
}
func (m *Statement) XXX_DiscardUnknown() {
	xxx_messageInfo_Statement.DiscardUnknown(m)
}

var xxx_messageInfo_Statement proto.InternalMessageInfo

func (m *Statement) GetH1() string {
	if m != nil {
		return m.H1
	}
	return ""
}

func (m *Statement) GetH2() string {
	if m != nil {
		return m.H2
	}
	return ""
}

type Statement1 struct {
	H1                   string   `protobuf:"bytes,1,opt,name=h1,proto3" json:"h1,omitempty"`
	H2                   string   `protobuf:"bytes,2,opt,name=h2,proto3" json:"h2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Statement1) Reset()         { *m = Statement1{} }
func (m *Statement1) String() string { return proto.CompactTextString(m) }
func (*Statement1) ProtoMessage()    {}
func (*Statement1) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{2}
}
func (m *Statement1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Statement1.Unmarshal(m, b)
}
func (m *Statement1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Statement1.Marshal(b, m, deterministic)
}
func (m *Statement1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Statement1.Merge(m, src)
}
func (m *Statement1) XXX_Size() int {
	return xxx_messageInfo_Statement1.Size(m)
}
func (m *Statement1) XXX_DiscardUnknown() {
	xxx_messageInfo_Statement1.DiscardUnknown(m)
}

var xxx_messageInfo_Statement1 proto.InternalMessageInfo

func (m *Statement1) GetH1() string {
	if m != nil {
		return m.H1
	}
	return ""
}

func (m *Statement1) GetH2() string {
	if m != nil {
		return m.H2
	}
	return ""
}

type RefundApi struct {
	Stm1                 *Statement1 `protobuf:"bytes,3,opt,name=stm1,proto3" json:"stm1,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RefundApi) Reset()         { *m = RefundApi{} }
func (m *RefundApi) String() string { return proto.CompactTextString(m) }
func (*RefundApi) ProtoMessage()    {}
func (*RefundApi) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{3}
}
func (m *RefundApi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefundApi.Unmarshal(m, b)
}
func (m *RefundApi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefundApi.Marshal(b, m, deterministic)
}
func (m *RefundApi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefundApi.Merge(m, src)
}
func (m *RefundApi) XXX_Size() int {
	return xxx_messageInfo_RefundApi.Size(m)
}
func (m *RefundApi) XXX_DiscardUnknown() {
	xxx_messageInfo_RefundApi.DiscardUnknown(m)
}

var xxx_messageInfo_RefundApi proto.InternalMessageInfo

func (m *RefundApi) GetStm1() *Statement1 {
	if m != nil {
		return m.Stm1
	}
	return nil
}

func init() {
	proto.RegisterEnum("core_service.RefundTransLogApi", RefundTransLogApi_name, RefundTransLogApi_value)
	proto.RegisterEnum("core_service.BODetailReconciliation_VoucherCode", BODetailReconciliation_VoucherCode_name, BODetailReconciliation_VoucherCode_value)
	proto.RegisterType((*BODetailReconciliation)(nil), "core_service.BODetailReconciliation")
	proto.RegisterType((*BODetailReconciliation_TimeAttribute)(nil), "core_service.BODetailReconciliation.TimeAttribute")
	proto.RegisterType((*BODetailReconciliation_CountableAttribute)(nil), "core_service.BODetailReconciliation.CountableAttribute")
	proto.RegisterType((*BODetailReconciliation_CountableAttribute_Transaction)(nil), "core_service.BODetailReconciliation.CountableAttribute.Transaction")
	proto.RegisterType((*BODetailReconciliation_Profile)(nil), "core_service.BODetailReconciliation.Profile")
	proto.RegisterType((*Statement)(nil), "core_service.Statement")
	proto.RegisterType((*Statement1)(nil), "core_service.Statement1")
	proto.RegisterType((*RefundApi)(nil), "core_service.RefundApi")
}

func init() { proto.RegisterFile("core.proto", fileDescriptor_f7e43720d1edc0fe) }

var fileDescriptor_f7e43720d1edc0fe = []byte{
	// 621 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x5d, 0x6f, 0xd3, 0x3c,
	0x14, 0xc7, 0x9f, 0x64, 0x6f, 0x4f, 0x4e, 0x5f, 0x56, 0x3c, 0x04, 0xa1, 0xd2, 0x44, 0x55, 0x4d,
	0xa8, 0xc0, 0x94, 0x91, 0x22, 0x81, 0x26, 0x71, 0xd3, 0x65, 0x1d, 0x0c, 0x55, 0xeb, 0xe4, 0x76,
	0x85, 0x5d, 0x59, 0x6e, 0xea, 0x2d, 0x51, 0x9b, 0x38, 0x4a, 0xdc, 0x49, 0xdb, 0x77, 0xe6, 0x82,
	0x6f, 0x80, 0x7c, 0xd2, 0x76, 0x9d, 0x06, 0xda, 0xe0, 0xce, 0xc7, 0x3e, 0xe7, 0xe7, 0xff, 0xf1,
	0xf9, 0x1b, 0xc0, 0x97, 0xa9, 0x70, 0x92, 0x54, 0x2a, 0x49, 0x8a, 0x7a, 0xcd, 0x32, 0x91, 0x5e,
	0x85, 0xbe, 0xa8, 0xbe, 0xbc, 0x94, 0xf2, 0x72, 0x22, 0xf6, 0xf0, 0x6c, 0x38, 0xbd, 0xd8, 0x53,
	0x61, 0x24, 0x32, 0xc5, 0xa3, 0x24, 0x4f, 0xaf, 0xff, 0xdc, 0x80, 0x67, 0x07, 0xdd, 0x43, 0xa1,
	0x78, 0x38, 0xa1, 0xc2, 0x97, 0xb1, 0x1f, 0x4e, 0x42, 0xae, 0x42, 0x19, 0x93, 0x7d, 0x00, 0x95,
	0xf2, 0x38, 0x63, 0xba, 0xc6, 0x36, 0x6b, 0x46, 0xa3, 0xd0, 0xac, 0x3a, 0x39, 0xd0, 0x99, 0x03,
	0x9d, 0xfe, 0x1c, 0x48, 0x2d, 0xcc, 0xd6, 0x31, 0xd9, 0x81, 0xf2, 0x4d, 0xc2, 0xb2, 0xeb, 0x4c,
	0x89, 0x88, 0xc5, 0x3c, 0x12, 0xf6, 0x4a, 0xcd, 0x68, 0x58, 0xb4, 0x78, 0x93, 0xf4, 0x70, 0xf3,
	0x84, 0x47, 0x82, 0xf4, 0xa0, 0x78, 0x25, 0xa7, 0x7e, 0x20, 0x52, 0xe6, 0xcb, 0x91, 0xb0, 0xa1,
	0x66, 0x34, 0xca, 0xcd, 0x77, 0xce, 0x72, 0x07, 0xce, 0xef, 0xc5, 0x39, 0x83, 0xbc, 0xd0, 0x93,
	0x23, 0x41, 0x0b, 0x57, 0xb7, 0x01, 0x39, 0x87, 0xb2, 0xd6, 0xcb, 0xb8, 0x52, 0x69, 0x38, 0x9c,
	0x2a, 0x61, 0x97, 0x50, 0x79, 0xf3, 0x51, 0x58, 0xad, 0xbe, 0x35, 0xaf, 0xa4, 0x25, 0xb5, 0x1c,
	0x92, 0x00, 0xb6, 0x7c, 0x39, 0x8d, 0x15, 0x1f, 0x4e, 0x96, 0xf9, 0x65, 0xe4, 0x7f, 0x7c, 0x14,
	0xdf, 0x9b, 0xd7, 0xdf, 0x5e, 0x42, 0xfc, 0x7b, 0x7b, 0xe4, 0x13, 0x98, 0x89, 0x6b, 0xaf, 0x21,
	0x78, 0xf7, 0x51, 0xe0, 0xd3, 0x54, 0x5e, 0x84, 0x13, 0x41, 0xcd, 0xc4, 0xad, 0x7e, 0x85, 0xd2,
	0x9d, 0x3e, 0xf4, 0x24, 0x53, 0xa1, 0xd2, 0xeb, 0x7c, 0x92, 0xc6, 0xc3, 0x93, 0xc4, 0x6c, 0x1d,
	0x57, 0x7f, 0x98, 0x40, 0xee, 0x8b, 0x26, 0x1f, 0x34, 0xf1, 0x62, 0x1a, 0x8f, 0x18, 0x4f, 0x42,
	0x9b, 0x20, 0xf1, 0xf9, 0x5d, 0xa1, 0x14, 0xcf, 0x5b, 0x49, 0xa8, 0x71, 0xb3, 0x25, 0xf9, 0x06,
	0xab, 0x23, 0xae, 0xb8, 0xfd, 0x14, 0x2b, 0xbc, 0x7f, 0x7c, 0x33, 0xa7, 0xaf, 0x9d, 0xc6, 0x7d,
	0x7d, 0x4c, 0x11, 0x48, 0xea, 0x50, 0x52, 0x89, 0x60, 0x43, 0x1e, 0x8f, 0x73, 0x33, 0xed, 0xa0,
	0xe1, 0x0a, 0x2a, 0x11, 0x07, 0x3c, 0x1e, 0xa3, 0x35, 0x5e, 0xc3, 0x4a, 0xa6, 0x22, 0xb4, 0xe2,
	0x3d, 0xb5, 0x3d, 0xc5, 0x95, 0x88, 0x44, 0xac, 0xa8, 0xce, 0x21, 0xdb, 0x00, 0xa1, 0xf6, 0x2e,
	0xce, 0xc6, 0x7e, 0x55, 0x33, 0x1a, 0x6b, 0xd4, 0xd2, 0x3b, 0x28, 0xa6, 0xfa, 0x1d, 0x0a, 0x4b,
	0x12, 0x48, 0x19, 0xcc, 0xb1, 0x8b, 0xef, 0x6a, 0x51, 0x73, 0xec, 0x62, 0xdc, 0xc4, 0x1f, 0xa3,
	0xe3, 0xe6, 0x5f, 0x5c, 0x5c, 0xdd, 0x86, 0x8d, 0xd9, 0x28, 0x09, 0x81, 0x55, 0xfd, 0x4d, 0x66,
	0x5c, 0x5c, 0xd7, 0x3d, 0x28, 0x2c, 0x39, 0x9f, 0x6c, 0xc3, 0x8b, 0x41, 0xf7, 0xcc, 0xfb, 0xd2,
	0xa6, 0xcc, 0xeb, 0x1e, 0xb6, 0xd9, 0xd9, 0x49, 0xef, 0xb4, 0xed, 0x1d, 0x1f, 0x1d, 0x7b, 0xed,
	0xc3, 0xca, 0x7f, 0x04, 0x60, 0x7d, 0xe0, 0xb1, 0xf3, 0x76, 0xaf, 0x62, 0x10, 0x0b, 0xd6, 0x06,
	0x1e, 0x3b, 0xe9, 0x56, 0xcc, 0xfa, 0x5b, 0xb0, 0x16, 0xb7, 0x6a, 0xad, 0xc1, 0x42, 0x7b, 0x80,
	0xda, 0x83, 0x85, 0xf6, 0xa0, 0x59, 0xdf, 0x05, 0x58, 0x24, 0xbb, 0x0f, 0x66, 0xef, 0x83, 0xb5,
	0x98, 0x3b, 0xd9, 0x85, 0xd5, 0x4c, 0x45, 0xee, 0xac, 0x6f, 0xfb, 0x0f, 0x7d, 0xbb, 0x14, 0xb3,
	0xde, 0x7c, 0x86, 0x27, 0x79, 0x29, 0xbe, 0x6c, 0x47, 0x5e, 0x6a, 0xc4, 0x16, 0x6c, 0xd2, 0x7e,
	0xeb, 0xb6, 0x2f, 0x6c, 0xab, 0x08, 0xff, 0xeb, 0xcd, 0xa3, 0xb3, 0x4e, 0xa7, 0x62, 0x90, 0x4d,
	0x28, 0xe8, 0xe8, 0xb4, 0x45, 0xfb, 0xc7, 0xad, 0x4e, 0xc5, 0x1c, 0xae, 0xa3, 0xa3, 0xdf, 0xff,
	0x0a, 0x00, 0x00, 0xff, 0xff, 0xb1, 0x03, 0x26, 0x36, 0x16, 0x05, 0x00, 0x00,
}
