// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core.proto

package core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BODetailReconciliation struct {
	// message TimeAttribute {
	//     google.protobuf.Timestamp retry_time = 1;
	// }
	CountableAttribute   *BODetailReconciliation_CountableAttribute `protobuf:"bytes,14,opt,name=countable_attribute,json=countableAttribute,proto3" json:"countable_attribute,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                   `json:"-"`
	XXX_unrecognized     []byte                                     `json:"-"`
	XXX_sizecache        int32                                      `json:"-"`
}

func (m *BODetailReconciliation) Reset()         { *m = BODetailReconciliation{} }
func (m *BODetailReconciliation) String() string { return proto.CompactTextString(m) }
func (*BODetailReconciliation) ProtoMessage()    {}
func (*BODetailReconciliation) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{0}
}

func (m *BODetailReconciliation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BODetailReconciliation.Unmarshal(m, b)
}
func (m *BODetailReconciliation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BODetailReconciliation.Marshal(b, m, deterministic)
}
func (m *BODetailReconciliation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BODetailReconciliation.Merge(m, src)
}
func (m *BODetailReconciliation) XXX_Size() int {
	return xxx_messageInfo_BODetailReconciliation.Size(m)
}
func (m *BODetailReconciliation) XXX_DiscardUnknown() {
	xxx_messageInfo_BODetailReconciliation.DiscardUnknown(m)
}

var xxx_messageInfo_BODetailReconciliation proto.InternalMessageInfo

func (m *BODetailReconciliation) GetCountableAttribute() *BODetailReconciliation_CountableAttribute {
	if m != nil {
		return m.CountableAttribute
	}
	return nil
}

type BODetailReconciliation_CountableAttribute struct {
	// @inject_tag: es:"merchantRefundAmount"
	MerchantRefundAmount int64    `protobuf:"varint,19,opt,name=merchant_refund_amount,json=merchantRefundAmount,proto3" json:"merchant_refund_amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BODetailReconciliation_CountableAttribute) Reset() {
	*m = BODetailReconciliation_CountableAttribute{}
}
func (m *BODetailReconciliation_CountableAttribute) String() string { return proto.CompactTextString(m) }
func (*BODetailReconciliation_CountableAttribute) ProtoMessage()    {}
func (*BODetailReconciliation_CountableAttribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{0, 0}
}

func (m *BODetailReconciliation_CountableAttribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BODetailReconciliation_CountableAttribute.Unmarshal(m, b)
}
func (m *BODetailReconciliation_CountableAttribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BODetailReconciliation_CountableAttribute.Marshal(b, m, deterministic)
}
func (m *BODetailReconciliation_CountableAttribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BODetailReconciliation_CountableAttribute.Merge(m, src)
}
func (m *BODetailReconciliation_CountableAttribute) XXX_Size() int {
	return xxx_messageInfo_BODetailReconciliation_CountableAttribute.Size(m)
}
func (m *BODetailReconciliation_CountableAttribute) XXX_DiscardUnknown() {
	xxx_messageInfo_BODetailReconciliation_CountableAttribute.DiscardUnknown(m)
}

var xxx_messageInfo_BODetailReconciliation_CountableAttribute proto.InternalMessageInfo

func (m *BODetailReconciliation_CountableAttribute) GetMerchantRefundAmount() int64 {
	if m != nil {
		return m.MerchantRefundAmount
	}
	return 0
}

func init() {
	proto.RegisterType((*BODetailReconciliation)(nil), "core.BODetailReconciliation")
	proto.RegisterType((*BODetailReconciliation_CountableAttribute)(nil), "core.BODetailReconciliation.CountableAttribute")
}

func init() { proto.RegisterFile("core.proto", fileDescriptor_f7e43720d1edc0fe) }

var fileDescriptor_f7e43720d1edc0fe = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xce, 0x2f, 0x4a,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x8e, 0x31, 0x72, 0x89, 0x39,
	0xf9, 0xbb, 0xa4, 0x96, 0x24, 0x66, 0xe6, 0x04, 0xa5, 0x26, 0xe7, 0xe7, 0x25, 0x67, 0xe6, 0x64,
	0x26, 0x96, 0x64, 0xe6, 0xe7, 0x09, 0x25, 0x70, 0x09, 0x27, 0xe7, 0x97, 0xe6, 0x95, 0x24, 0x26,
	0xe5, 0xa4, 0xc6, 0x27, 0x96, 0x94, 0x14, 0x65, 0x26, 0x95, 0x96, 0xa4, 0x4a, 0xf0, 0x29, 0x30,
	0x6a, 0x70, 0x1b, 0xe9, 0xeb, 0x81, 0x8d, 0xc2, 0xae, 0x55, 0xcf, 0x19, 0xa6, 0xcf, 0x11, 0xa6,
	0x2d, 0x48, 0x28, 0x19, 0x43, 0x4c, 0xca, 0x8b, 0x4b, 0x08, 0x53, 0xa5, 0x90, 0x09, 0x97, 0x58,
	0x6e, 0x6a, 0x51, 0x72, 0x46, 0x62, 0x5e, 0x49, 0x7c, 0x51, 0x6a, 0x5a, 0x69, 0x5e, 0x4a, 0x7c,
	0x62, 0x2e, 0x48, 0x99, 0x84, 0xb0, 0x02, 0xa3, 0x06, 0x73, 0x90, 0x08, 0x4c, 0x36, 0x08, 0x2c,
	0xe9, 0x08, 0x96, 0x4b, 0x62, 0x03, 0xfb, 0xca, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x3b, 0xe2,
	0x9a, 0x81, 0xe3, 0x00, 0x00, 0x00,
}
