// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core.proto

package core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListCITransactionsRequest struct {
	MTransId             string   `protobuf:"bytes,1,opt,name=m_trans_id,json=mTransId,proto3" json:"m_trans_id,omitempty"`
	ZpTransId            string   `protobuf:"bytes,2,opt,name=zp_trans_id,json=zpTransId,proto3" json:"zp_trans_id,omitempty"`
	MId                  string   `protobuf:"bytes,3,opt,name=m_id,json=mId,proto3" json:"m_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCITransactionsRequest) Reset()         { *m = ListCITransactionsRequest{} }
func (m *ListCITransactionsRequest) String() string { return proto.CompactTextString(m) }
func (*ListCITransactionsRequest) ProtoMessage()    {}
func (*ListCITransactionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7e43720d1edc0fe, []int{0}
}

func (m *ListCITransactionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCITransactionsRequest.Unmarshal(m, b)
}
func (m *ListCITransactionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCITransactionsRequest.Marshal(b, m, deterministic)
}
func (m *ListCITransactionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCITransactionsRequest.Merge(m, src)
}
func (m *ListCITransactionsRequest) XXX_Size() int {
	return xxx_messageInfo_ListCITransactionsRequest.Size(m)
}
func (m *ListCITransactionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCITransactionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCITransactionsRequest proto.InternalMessageInfo

func (m *ListCITransactionsRequest) GetMTransId() string {
	if m != nil {
		return m.MTransId
	}
	return ""
}

func (m *ListCITransactionsRequest) GetZpTransId() string {
	if m != nil {
		return m.ZpTransId
	}
	return ""
}

func (m *ListCITransactionsRequest) GetMId() string {
	if m != nil {
		return m.MId
	}
	return ""
}

func init() {
	proto.RegisterType((*ListCITransactionsRequest)(nil), "core.ListCITransactionsRequest")
}

func init() { proto.RegisterFile("core.proto", fileDescriptor_f7e43720d1edc0fe) }

var fileDescriptor_f7e43720d1edc0fe = []byte{
	// 127 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xce, 0x2f, 0x4a,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x72, 0xb8, 0x24, 0x7d, 0x32,
	0x8b, 0x4b, 0x9c, 0x3d, 0x43, 0x8a, 0x12, 0xf3, 0x8a, 0x13, 0x93, 0x4b, 0x32, 0xf3, 0xf3, 0x8a,
	0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x64, 0xb8, 0xb8, 0x72, 0xe3, 0x4b, 0x40, 0x12,
	0xf1, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x1c, 0xb9, 0x60, 0x95, 0x9e, 0x29,
	0x42, 0x72, 0x5c, 0xdc, 0x55, 0x05, 0x08, 0x69, 0x26, 0xb0, 0x34, 0x67, 0x55, 0x01, 0x4c, 0x5e,
	0x90, 0x8b, 0x25, 0x17, 0x24, 0xc1, 0x0c, 0x96, 0x60, 0xce, 0xf5, 0x4c, 0x49, 0x62, 0x03, 0x5b,
	0x6d, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x8f, 0xc4, 0xbd, 0x21, 0x88, 0x00, 0x00, 0x00,
}
