// Code generated by protoc-gen-go. DO NOT EDIT.
// source: middleware.proto

package middleware

import (
	fmt "fmt"
	proto1 "git.zapa.cloud/merchant-tools/helper/proto"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BODetailReconciliation struct {
	FromDate *proto1.Date `protobuf:"bytes,1,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	// //     // message TimeAttribute {
	// //     //     google.protobuf.Timestamp retry_time = 1;
	// //     // }
	CountableAttribute *BODetailReconciliation_CountableAttribute `protobuf:"bytes,14,opt,name=countable_attribute,json=countableAttribute,proto3" json:"countable_attribute,omitempty"`
	//     enum VoucherCode{
	//         VOUCHER_CODE_UNSPECIFICED    = 0;
	//         VC_YES   = 1;
	//         VC_NO    = 2;
	//     }
	TransTime            *timestamp.Timestamp `protobuf:"bytes,24,opt,name=trans_time,json=transTime,proto3" json:"trans_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BODetailReconciliation) Reset()         { *m = BODetailReconciliation{} }
func (m *BODetailReconciliation) String() string { return proto.CompactTextString(m) }
func (*BODetailReconciliation) ProtoMessage()    {}
func (*BODetailReconciliation) Descriptor() ([]byte, []int) {
	return fileDescriptor_10e8b4c446957f50, []int{0}
}

func (m *BODetailReconciliation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BODetailReconciliation.Unmarshal(m, b)
}
func (m *BODetailReconciliation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BODetailReconciliation.Marshal(b, m, deterministic)
}
func (m *BODetailReconciliation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BODetailReconciliation.Merge(m, src)
}
func (m *BODetailReconciliation) XXX_Size() int {
	return xxx_messageInfo_BODetailReconciliation.Size(m)
}
func (m *BODetailReconciliation) XXX_DiscardUnknown() {
	xxx_messageInfo_BODetailReconciliation.DiscardUnknown(m)
}

var xxx_messageInfo_BODetailReconciliation proto.InternalMessageInfo

func (m *BODetailReconciliation) GetFromDate() *proto1.Date {
	if m != nil {
		return m.FromDate
	}
	return nil
}

func (m *BODetailReconciliation) GetCountableAttribute() *BODetailReconciliation_CountableAttribute {
	if m != nil {
		return m.CountableAttribute
	}
	return nil
}

func (m *BODetailReconciliation) GetTransTime() *timestamp.Timestamp {
	if m != nil {
		return m.TransTime
	}
	return nil
}

type BODetailReconciliation_CountableAttribute struct {
	// @inject_tag: es:"merchantRefundAmount"
	// int64 merchant_refund_amount = 19;
	Data *BODetailReconciliation_CountableAttribute_Data `protobuf:"bytes,20,opt,name=data,proto3" json:"data,omitempty"`
	// @inject_tag: es:"refundPercentFeeNotVat"
	// double return_percent_fee_not_vat = 28;
	// @inject_tag: es:"tpeBankCode"
	TpeBankCode string `protobuf:"bytes,36,opt,name=tpe_bank_code,json=tpeBankCode,proto3" json:"tpe_bank_code,omitempty"`
	Hello       *Hello `protobuf:"bytes,3,opt,name=hello,proto3" json:"hello,omitempty"`
	// @inject_tag: es:"itemCount"
	ItemCount            int32    `protobuf:"varint,38,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BODetailReconciliation_CountableAttribute) Reset() {
	*m = BODetailReconciliation_CountableAttribute{}
}
func (m *BODetailReconciliation_CountableAttribute) String() string { return proto.CompactTextString(m) }
func (*BODetailReconciliation_CountableAttribute) ProtoMessage()    {}
func (*BODetailReconciliation_CountableAttribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_10e8b4c446957f50, []int{0, 0}
}

func (m *BODetailReconciliation_CountableAttribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BODetailReconciliation_CountableAttribute.Unmarshal(m, b)
}
func (m *BODetailReconciliation_CountableAttribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BODetailReconciliation_CountableAttribute.Marshal(b, m, deterministic)
}
func (m *BODetailReconciliation_CountableAttribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BODetailReconciliation_CountableAttribute.Merge(m, src)
}
func (m *BODetailReconciliation_CountableAttribute) XXX_Size() int {
	return xxx_messageInfo_BODetailReconciliation_CountableAttribute.Size(m)
}
func (m *BODetailReconciliation_CountableAttribute) XXX_DiscardUnknown() {
	xxx_messageInfo_BODetailReconciliation_CountableAttribute.DiscardUnknown(m)
}

var xxx_messageInfo_BODetailReconciliation_CountableAttribute proto.InternalMessageInfo

func (m *BODetailReconciliation_CountableAttribute) GetData() *BODetailReconciliation_CountableAttribute_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *BODetailReconciliation_CountableAttribute) GetTpeBankCode() string {
	if m != nil {
		return m.TpeBankCode
	}
	return ""
}

func (m *BODetailReconciliation_CountableAttribute) GetHello() *Hello {
	if m != nil {
		return m.Hello
	}
	return nil
}

func (m *BODetailReconciliation_CountableAttribute) GetItemCount() int32 {
	if m != nil {
		return m.ItemCount
	}
	return 0
}

type BODetailReconciliation_CountableAttribute_Data struct {
	K1                   string                                        `protobuf:"bytes,1,opt,name=k1,proto3" json:"k1,omitempty"`
	K2                   string                                        `protobuf:"bytes,2,opt,name=k2,proto3" json:"k2,omitempty"`
	Hello                *Hello                                        `protobuf:"bytes,3,opt,name=hello,proto3" json:"hello,omitempty"`
	Hi                   *BODetailReconciliation_CountableAttribute_Hi `protobuf:"bytes,4,opt,name=hi,proto3" json:"hi,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *BODetailReconciliation_CountableAttribute_Data) Reset() {
	*m = BODetailReconciliation_CountableAttribute_Data{}
}
func (m *BODetailReconciliation_CountableAttribute_Data) String() string {
	return proto.CompactTextString(m)
}
func (*BODetailReconciliation_CountableAttribute_Data) ProtoMessage() {}
func (*BODetailReconciliation_CountableAttribute_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_10e8b4c446957f50, []int{0, 0, 0}
}

func (m *BODetailReconciliation_CountableAttribute_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BODetailReconciliation_CountableAttribute_Data.Unmarshal(m, b)
}
func (m *BODetailReconciliation_CountableAttribute_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BODetailReconciliation_CountableAttribute_Data.Marshal(b, m, deterministic)
}
func (m *BODetailReconciliation_CountableAttribute_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BODetailReconciliation_CountableAttribute_Data.Merge(m, src)
}
func (m *BODetailReconciliation_CountableAttribute_Data) XXX_Size() int {
	return xxx_messageInfo_BODetailReconciliation_CountableAttribute_Data.Size(m)
}
func (m *BODetailReconciliation_CountableAttribute_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_BODetailReconciliation_CountableAttribute_Data.DiscardUnknown(m)
}

var xxx_messageInfo_BODetailReconciliation_CountableAttribute_Data proto.InternalMessageInfo

func (m *BODetailReconciliation_CountableAttribute_Data) GetK1() string {
	if m != nil {
		return m.K1
	}
	return ""
}

func (m *BODetailReconciliation_CountableAttribute_Data) GetK2() string {
	if m != nil {
		return m.K2
	}
	return ""
}

func (m *BODetailReconciliation_CountableAttribute_Data) GetHello() *Hello {
	if m != nil {
		return m.Hello
	}
	return nil
}

func (m *BODetailReconciliation_CountableAttribute_Data) GetHi() *BODetailReconciliation_CountableAttribute_Hi {
	if m != nil {
		return m.Hi
	}
	return nil
}

type BODetailReconciliation_CountableAttribute_Hi struct {
	Hk                   int32    `protobuf:"varint,1,opt,name=hk,proto3" json:"hk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BODetailReconciliation_CountableAttribute_Hi) Reset() {
	*m = BODetailReconciliation_CountableAttribute_Hi{}
}
func (m *BODetailReconciliation_CountableAttribute_Hi) String() string {
	return proto.CompactTextString(m)
}
func (*BODetailReconciliation_CountableAttribute_Hi) ProtoMessage() {}
func (*BODetailReconciliation_CountableAttribute_Hi) Descriptor() ([]byte, []int) {
	return fileDescriptor_10e8b4c446957f50, []int{0, 0, 1}
}

func (m *BODetailReconciliation_CountableAttribute_Hi) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BODetailReconciliation_CountableAttribute_Hi.Unmarshal(m, b)
}
func (m *BODetailReconciliation_CountableAttribute_Hi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BODetailReconciliation_CountableAttribute_Hi.Marshal(b, m, deterministic)
}
func (m *BODetailReconciliation_CountableAttribute_Hi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BODetailReconciliation_CountableAttribute_Hi.Merge(m, src)
}
func (m *BODetailReconciliation_CountableAttribute_Hi) XXX_Size() int {
	return xxx_messageInfo_BODetailReconciliation_CountableAttribute_Hi.Size(m)
}
func (m *BODetailReconciliation_CountableAttribute_Hi) XXX_DiscardUnknown() {
	xxx_messageInfo_BODetailReconciliation_CountableAttribute_Hi.DiscardUnknown(m)
}

var xxx_messageInfo_BODetailReconciliation_CountableAttribute_Hi proto.InternalMessageInfo

func (m *BODetailReconciliation_CountableAttribute_Hi) GetHk() int32 {
	if m != nil {
		return m.Hk
	}
	return 0
}

// enum RefundTransLogApi {
//     RTA_UNSPECIFIED = 0;
//     RTA_FULL        = 1;
//     RTA_PARTIAL     = 2;
// }
type Hello struct {
	H1                   string   `protobuf:"bytes,1,opt,name=h1,proto3" json:"h1,omitempty"`
	H2                   string   `protobuf:"bytes,2,opt,name=h2,proto3" json:"h2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hello) Reset()         { *m = Hello{} }
func (m *Hello) String() string { return proto.CompactTextString(m) }
func (*Hello) ProtoMessage()    {}
func (*Hello) Descriptor() ([]byte, []int) {
	return fileDescriptor_10e8b4c446957f50, []int{1}
}

func (m *Hello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hello.Unmarshal(m, b)
}
func (m *Hello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hello.Marshal(b, m, deterministic)
}
func (m *Hello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hello.Merge(m, src)
}
func (m *Hello) XXX_Size() int {
	return xxx_messageInfo_Hello.Size(m)
}
func (m *Hello) XXX_DiscardUnknown() {
	xxx_messageInfo_Hello.DiscardUnknown(m)
}

var xxx_messageInfo_Hello proto.InternalMessageInfo

func (m *Hello) GetH1() string {
	if m != nil {
		return m.H1
	}
	return ""
}

func (m *Hello) GetH2() string {
	if m != nil {
		return m.H2
	}
	return ""
}

func init() {
	proto.RegisterType((*BODetailReconciliation)(nil), "middleware.BODetailReconciliation")
	proto.RegisterType((*BODetailReconciliation_CountableAttribute)(nil), "middleware.BODetailReconciliation.CountableAttribute")
	proto.RegisterType((*BODetailReconciliation_CountableAttribute_Data)(nil), "middleware.BODetailReconciliation.CountableAttribute.Data")
	proto.RegisterType((*BODetailReconciliation_CountableAttribute_Hi)(nil), "middleware.BODetailReconciliation.CountableAttribute.Hi")
	proto.RegisterType((*Hello)(nil), "middleware.Hello")
}

func init() { proto.RegisterFile("middleware.proto", fileDescriptor_10e8b4c446957f50) }

var fileDescriptor_10e8b4c446957f50 = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x4f, 0x8b, 0xd3, 0x40,
	0x18, 0xc6, 0x49, 0xb6, 0x15, 0xf3, 0x2e, 0x2e, 0x3a, 0x2e, 0x32, 0x04, 0xc4, 0x52, 0xc4, 0xed,
	0xc5, 0x84, 0xad, 0x2c, 0xa8, 0x37, 0x77, 0xf7, 0xd0, 0x93, 0xc2, 0xe0, 0x3d, 0x4c, 0x92, 0xb7,
	0x9d, 0x21, 0x93, 0x4c, 0x48, 0xdf, 0x22, 0x7a, 0xf4, 0x5b, 0xf8, 0x2d, 0xfd, 0x08, 0x32, 0x6f,
	0x9b, 0x75, 0x61, 0x3d, 0x48, 0x6f, 0x79, 0xff, 0x3d, 0xcf, 0x2f, 0xcf, 0xc0, 0xd3, 0xd6, 0xd6,
	0xb5, 0xc3, 0x6f, 0x7a, 0xc0, 0xac, 0x1f, 0x3c, 0x79, 0x01, 0x7f, 0x3b, 0xe9, 0xab, 0x8d, 0xf7,
	0x1b, 0x87, 0x39, 0x4f, 0xca, 0xdd, 0x3a, 0x27, 0xdb, 0xe2, 0x96, 0x74, 0xdb, 0xef, 0x97, 0xd3,
	0xab, 0x8d, 0xa5, 0xec, 0x87, 0xee, 0x75, 0x56, 0x39, 0xbf, 0xab, 0xf3, 0x16, 0x87, 0xca, 0xe8,
	0x8e, 0xde, 0x92, 0xf7, 0x6e, 0x9b, 0x1b, 0x74, 0x3d, 0x0e, 0xfb, 0xf3, 0x9c, 0xbe, 0xf7, 0x07,
	0x8f, 0xf9, 0xef, 0x09, 0xbc, 0xb8, 0xfe, 0x72, 0x8b, 0xa4, 0xad, 0x53, 0x58, 0xf9, 0xae, 0xb2,
	0xce, 0x6a, 0xb2, 0xbe, 0x13, 0x19, 0x24, 0xeb, 0xc1, 0xb7, 0x45, 0xad, 0x09, 0x65, 0x34, 0x8b,
	0x16, 0xa7, 0xcb, 0x67, 0xd9, 0x1e, 0x23, 0x63, 0x85, 0x5b, 0x4d, 0xa8, 0x1e, 0x87, 0x9d, 0xf0,
	0x25, 0xd6, 0xf0, 0xbc, 0xf2, 0xbb, 0x8e, 0x74, 0xe9, 0xb0, 0xd0, 0x44, 0x83, 0x2d, 0x77, 0x84,
	0xf2, 0x8c, 0x2f, 0xaf, 0xb2, 0x7b, 0xbf, 0xf7, 0x6f, 0xc3, 0xec, 0x66, 0xbc, 0xfe, 0x34, 0x1e,
	0x2b, 0x51, 0x3d, 0xe8, 0x89, 0x0f, 0x00, 0x34, 0xe8, 0x6e, 0x5b, 0x84, 0x08, 0xa4, 0x64, 0xf9,
	0x74, 0x04, 0x1b, 0xf3, 0xc9, 0xbe, 0x8e, 0xf9, 0xa8, 0x84, 0xb7, 0x43, 0x9d, 0xfe, 0x3c, 0x01,
	0xf1, 0xd0, 0x45, 0x7c, 0x86, 0x49, 0xad, 0x49, 0xcb, 0x73, 0xd6, 0xfa, 0x78, 0x14, 0x6a, 0x48,
	0x43, 0x2b, 0xd6, 0x11, 0x73, 0x78, 0x42, 0x3d, 0x16, 0xa5, 0xee, 0x9a, 0xa2, 0xf2, 0x35, 0xca,
	0xd7, 0xb3, 0x68, 0x91, 0xa8, 0x53, 0xea, 0xf1, 0x5a, 0x77, 0xcd, 0x8d, 0xaf, 0x51, 0x5c, 0xc0,
	0xd4, 0xa0, 0x73, 0x5e, 0x9e, 0x1c, 0x92, 0xbd, 0x67, 0xba, 0x0a, 0x03, 0xb5, 0x9f, 0x8b, 0x97,
	0x00, 0x96, 0xb0, 0x2d, 0x38, 0x09, 0xf9, 0x66, 0x16, 0x2d, 0xa6, 0x2a, 0x09, 0x1d, 0x66, 0x48,
	0x7f, 0x45, 0x30, 0x09, 0xd6, 0xe2, 0x0c, 0xe2, 0xe6, 0x92, 0xdf, 0x29, 0x51, 0x71, 0x73, 0xc9,
	0xf5, 0x52, 0xc6, 0x87, 0x7a, 0xf9, 0xff, 0x86, 0x2b, 0x88, 0x8d, 0x95, 0x13, 0xde, 0x7a, 0x7f,
	0x5c, 0x16, 0x2b, 0xab, 0x62, 0x63, 0xd3, 0x73, 0x88, 0x57, 0x36, 0x80, 0x98, 0x86, 0xc1, 0xa6,
	0x2a, 0x36, 0xcd, 0xfc, 0x02, 0xa6, 0xec, 0xc7, 0x83, 0x3b, 0x62, 0xc3, 0xc4, 0xe6, 0x8e, 0xd8,
	0x2c, 0xcb, 0x47, 0xfc, 0x98, 0xef, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x85, 0x5e, 0xeb, 0x45,
	0x1a, 0x03, 0x00, 0x00,
}
