// Code generated by protoc-gen-go. DO NOT EDIT.
// source: middleware.proto

package middleware

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListCITransactionsRequest struct {
	MTransId             string   `protobuf:"bytes,1,opt,name=m_trans_id,json=mTransId,proto3" json:"m_trans_id,omitempty"`
	ZpTransId            string   `protobuf:"bytes,2,opt,name=zp_trans_id,json=zpTransId,proto3" json:"zp_trans_id,omitempty"`
	MerchantId           string   `protobuf:"bytes,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	MId                  string   `protobuf:"bytes,4,opt,name=m_id,json=mId,proto3" json:"m_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCITransactionsRequest) Reset()         { *m = ListCITransactionsRequest{} }
func (m *ListCITransactionsRequest) String() string { return proto.CompactTextString(m) }
func (*ListCITransactionsRequest) ProtoMessage()    {}
func (*ListCITransactionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10e8b4c446957f50, []int{0}
}

func (m *ListCITransactionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCITransactionsRequest.Unmarshal(m, b)
}
func (m *ListCITransactionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCITransactionsRequest.Marshal(b, m, deterministic)
}
func (m *ListCITransactionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCITransactionsRequest.Merge(m, src)
}
func (m *ListCITransactionsRequest) XXX_Size() int {
	return xxx_messageInfo_ListCITransactionsRequest.Size(m)
}
func (m *ListCITransactionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCITransactionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCITransactionsRequest proto.InternalMessageInfo

func (m *ListCITransactionsRequest) GetMTransId() string {
	if m != nil {
		return m.MTransId
	}
	return ""
}

func (m *ListCITransactionsRequest) GetZpTransId() string {
	if m != nil {
		return m.ZpTransId
	}
	return ""
}

func (m *ListCITransactionsRequest) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *ListCITransactionsRequest) GetMId() string {
	if m != nil {
		return m.MId
	}
	return ""
}

func init() {
	proto.RegisterType((*ListCITransactionsRequest)(nil), "middleware.ListCITransactionsRequest")
}

func init() { proto.RegisterFile("middleware.proto", fileDescriptor_10e8b4c446957f50) }

var fileDescriptor_10e8b4c446957f50 = []byte{
	// 156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0xcd, 0x4c, 0x49,
	0xc9, 0x49, 0x2d, 0x4f, 0x2c, 0x4a, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42, 0x88,
	0x28, 0xf5, 0x32, 0x72, 0x49, 0xfa, 0x64, 0x16, 0x97, 0x38, 0x7b, 0x86, 0x14, 0x25, 0xe6, 0x15,
	0x27, 0x26, 0x97, 0x64, 0xe6, 0xe7, 0x15, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xc9,
	0x70, 0x71, 0xe5, 0xc6, 0x97, 0x80, 0x24, 0xe2, 0x33, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x83, 0x38, 0x72, 0xc1, 0x2a, 0x3d, 0x53, 0x84, 0xe4, 0xb8, 0xb8, 0xab, 0x0a, 0x10, 0xd2, 0x4c,
	0x60, 0x69, 0xce, 0xaa, 0x02, 0x98, 0xbc, 0x3c, 0x17, 0x77, 0x6e, 0x6a, 0x51, 0x72, 0x46, 0x62,
	0x5e, 0x09, 0x48, 0x9e, 0x19, 0x2c, 0xcf, 0x05, 0x13, 0xf2, 0x4c, 0x11, 0x12, 0xe4, 0x62, 0xc9,
	0x05, 0xc9, 0xb0, 0x80, 0x65, 0x98, 0x73, 0x3d, 0x53, 0x92, 0xd8, 0xc0, 0x4e, 0x34, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x89, 0x20, 0x93, 0xe1, 0xb6, 0x00, 0x00, 0x00,
}
